
name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'
    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s-manifests/
